name: update_deno

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: oprypin/fin-latest-tag@v1
        id: denoVersion
        with:
          repository: denoland/deno
          prefix: v

      - uses: actions/checkout@v2
        
      - name: echoes Deno version
        run: echo "Deno is at version ${{ steps.denoVersion.outputs.tag }}"
